source "https://rubygems.org"

ruby "3.3.4"

gem "jekyll", "~> 4.2"
gem "minima", "~> 2.5"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "faraday-retry", "~> 1.0"
